let foods = [
  {
    name: ["Үхрийн шарсан хавирга", "Dry Fry Beef Short Ribs"],
    pic: "./beef.png",
    price: 55000,
    category: "2rhool",
    description: ["үхрийн хавирга, эвэр чинжүү, брокколи, үрлэн помидор, ногоон ногооны салат, будаа, гар аргаар хийсэн АЗИ соус ", "beef short ribs, green chilli pepper, brocolli, cherry tomato, green lattuce salad, rice, hand made asain sous "],
  },
  {
    name: ["Авакадо салат", "Avacodo Salad"],
    pic: "./avacado.png",
    price: 18000,
    category: "Salad",
    description: ["Саладны навч, рокет навч, үрлэн помидор, огурцы, алмонд самар, хатаасан үзэм, авокадо, аньсны соус", "green lettuce, rocket lattuce, cherry tomate, cucumber, almond, dry raisin, avocado, lingonberry sous"],
  },
  {
    name: ["Хавай пицца", "Hawai pizza"],
    pic: "./hawai.png",
    price: 45000,
    category: "pizza",
    description: ["гурил, соус, моццерелла, бекон, ананас, амталсан масло ", "pizza flour, hand made sous, mozzeralla, becon, pineapple, garlic butter"],
  },
  {
    name: ["Яки нику", "Yakiiniku udon"],
    pic: "./Yaki_Niku.png",
    price: 25000,
    category: "2rhool",
    description: ["үхрийн мах, сонгино, будаа, өндөг, амталсан цагаан гаа, өндөг", "rice, beef, onion egg, sweet ginger, egg"],
  },
  {
    name: ["Удон гоймонтой шөл", "Udon noodle"],
    pic: "./Udon_Noodle.png",
    price: 20000,
    category: "sholtei hool",
    description: ["удан ноймон, тахианы гуяны мах, юуцай, лууван, наруто өндөг", "udon noodle, chicken, pack choi, carrot, naruto egg"],
  },
  {
    name: ["Яки удон", "Yakii udon"],
    pic: "./Yaki_Udon.png",
    price: 25000,
    category: "sholtei hool",
    description: ["удон гоймон, үхрийн мах, юуцай, лууван, наруто өндөг", "udon noodle, beff, pack choi, carrot, naruto egg"],
  },
  {
    name: ["Халуун ногоотой, тахиан махтай пицца", "Chicken spicy pizza"],
    pic: "./Chicken-spicy-pizza.png",
    price: 45000,
    category: "pizza",
    description: ["гурил, соус, моццерелла, тахианы мах, чинжүү, халуун ногойтой соус, чинжүү, амталсан соус", "pizza flour, hand made sous, mozzeralla, chicken, jallapenho, spicy sous, harlic butter"],
  },
  {
    name: ["Пеперони", "Pepperoni pizza"],
    pic: "./pepperoni-pizza.png",
    price: 45000,
    category: "pizza",
    description: ["гурил, соус, моццерелла, пепперони, амталсан масло", "pizza flour, hand made sous, mozzeralla, pepperoni, garlic butter"],
  },
  {
    name: ["Маханд дурлагсад пицца", "Meat lovers pizza"],
    pic: "./Meat_Lovers.png",
    price: 45000,
    category: "pizza",
    description: ["гурил, соус, моццерелла, бекон, үхрийн мах, тахианы мах, хар олив, амталсан масло", "flour, hand made sous, mozzeralla, beef chicken, bacon, black oliver, garlic butter"],
  },
  {
    name: ["Самгёопсал 2 хүнийх", "Samgyeopsal 2 person"],
    pic: "./Samgyeopsal.png",
    price: 50000,
    category: "2rhool",
    description: ["Гахайн мах, 2 төрлийн мөөг, сонгино, кимчи, будаа", "Samgyeopsal, green lattuce, 2 kind off mushroom, onion, kimchi samjan, rice"],
  },
  {
    name: ["Самгёопсал 4 хүнийх", "Samgyeopsal 4 person"],
    pic: "./Samgyeopsal.png",
    price: 70000,
    category: "2rhool",
    description: ["Гахайн мах, 2 төрлийн мөөг, сонгино, кимчи, будаа", "Samgyeopsal, green lattuce, 2 kind off mushroom, onion, kimchi samjan, rice"],
  },
  {
    name: ["Начо", "Nacho"],
    pic: "./Nacho.png",
    price: 18000,
    category: "Salad",
    description: ["тортилла гурил, блогнизь соус, салса, 2 төрлийн маёо соус", "tortilla flour, blognese sous, salsa, mayo sous chilli mayo sous"],
  },
  
  {
    name: ["Үхрийн хэлэн салат", "Beef Tongue salad"],
    pic: "./Beef_tongue_salad.png",
    price: 20000,
    category: "Salad",
    description: ["Салатны навч, рокет навч, үрлэн помидор, огурцы, үхрийн хэл, гүнждийн үртэй соус, бийф соус,", ""],
  },
  {
    name: ["Карри", "Karaage"],
    pic: "./Katsu_curry.png",
    price: 25000,
    category: "2r hool",
    description: ["амталсан тахианы гуя, рокет навч, лемон, будаа, мисо шөл", "chiken, rocket lettuce, lemon, mayio sous, rice, miso soup"],
  },
  {
    name: ["Карри соустай тахиа", "Chicken katsuu with carry sous"],
    pic: "./chicken.png",
    price: 25000,
    category: "2rhool",
    description: ["амталсан тахианы цээж, брокколи, карри соус, будаа, мисо шөл", "chicken, broccoli, rice, carry sous, miso soup"],
  },
];
export default foods;